workspace("flow2d")
    configurations({ "debug", "release" })
    location( "build" )

    filter("configurations:debug")
        defines({ "DEBUG" })
        flags({ "Symbols" })

    filter("configurations:release")
        defines({ "NDEBUG" })
        optimize( "On" )

    project("flow2d")
        kind( "StaticLib" )
        language( "C++" )
        buildoptions({"-std=c++11", "-stdlib=libc++"})
        files({ "source/**.cpp" })
        sysincludedirs({ "source", "3rd/glm" })
        targetdir( "build/libs" )

workspace("chore")
    configurations( "debug" )
    location( "build/test" )
    defines({ "DEBUG" })
    flags({ "Symbols" })
    kind( "ConsoleApp" )
    libdirs({ "build/libs" })
    sysincludedirs({ "source", "3rd/catch/include", "3rd/glm" })
    language( "C++" )
    buildoptions({"-std=c++11", "-stdlib=libc++"})
    targetdir( "build/bin" )

    project( "test" )
        links({ "flow2d" })
        files({ "test/*_test.cpp" })

